highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://JyunYiShih.github.io/
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: "/"
title: Junyi Shi's Personal Page
name: Junyi 
name: Shi
name：施俊屹
email: syf758521@foxmail.com
email_full: mailto:syf758521@foxmail.com
website: JunyiShi.github.io
website_full: https://JyunYiShih.github.io/
github: JyunYiShih
twitter: twitter
tel: 
tel_full: 
google_maps: 
address:
  street: 
  postcode: Graduate
  city: HIT
  country: China
google_analytics: 

# needed for travis-ci build
exclude: [vendor]
